# Generated by Django 5.2.3 on 2025-06-20 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic Plan'), ('premium', 'Premium Plan'), ('pro', 'Pro Plan')], max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', '3 Months'), ('biannual', '6 Months'), ('annual', 'Annual')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('assessment_credits', models.PositiveIntegerField(help_text='Number of AI assessments included')),
                ('practice_tasks_limit', models.PositiveIntegerField(blank=True, help_text='Maximum practice tasks (null = unlimited)', null=True)),
                ('priority_support', models.BooleanField(default=False)),
                ('advanced_analytics', models.BooleanField(default=False)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('stripe_product_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list, help_text='List of features for this plan')),
            ],
            options={
                'db_table': 'subscriptions_plan',
                'ordering': ['sort_order', 'price'],
                'indexes': [models.Index(fields=['is_active', 'plan_type'], name='subscriptio_is_acti_a2b0e3_idx'), models.Index(fields=['billing_period'], name='subscriptio_billing_835e9b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('unpaid', 'Unpaid'), ('paused', 'Paused'), ('expired', 'Expired')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('assessment_credits_used', models.PositiveIntegerField(default=0)),
                ('assessment_credits_remaining', models.PositiveIntegerField(default=0)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_user_subscription',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_type', models.CharField(choices=[('assessment', 'AI Assessment'), ('practice', 'Practice Session'), ('export', 'Data Export')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('billable', models.BooleanField(default=True)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'subscriptions_usage_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('failure_reason', models.TextField(blank=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.usersubscription')),
            ],
            options={
                'db_table': 'subscriptions_payment_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_7d5d03_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__1e59df_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['user', 'usage_type'], name='subscriptio_user_id_4932dd_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['created_at'], name='subscriptio_created_ba78fc_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['billable', 'billed_at'], name='subscriptio_billabl_d39633_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_c6149b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['stripe_payment_intent_id'], name='subscriptio_stripe__d5c3ca_idx'),
        ),
    ]
